apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ajf/homekube.git
    targetRevision: HEAD
    path: clusters/homelab/prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-system
