apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- includeCRDs: true
  name: kube-prometheus-stack
  namespace: prometheus-system
  releaseName: prom
  repo: https://prometheus-community.github.io/helm-charts
  valuesFile: values.yaml
  version: 58.7.2

patches:
- patch: |-
    - op: add
      path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
      value: "Replace=true"
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: prometheuses.monitoring.coreos.com
    version: v1
- patch: |-
    - op: add
      path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
      value: "Replace=true"
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: prometheusagents.monitoring.coreos.com
    version: v1
- patch: |-
    - op: add
      path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
      value: "Replace=true"
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: alertmanagers.monitoring.coreos.com
    version: v1
- patch: |-
    - op: add
      path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
      value: "Replace=true"
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: thanosrulers.monitoring.coreos.com
    version: v1
